apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://observe-prometheus:9090
    isDefault: true
    uid: observe-prometheus
    jsonData:
      timeInterval: "15s"

  - name: Loki
    type: loki
    access: proxy
    url: http://observe-loki:3100
    uid: observe-loki
    jsonData:
      maxLines: 1000
