/**
 * Hosts de exemplo para R-Observe
 * Edite ou monte um volume com sua configuração real de hosts.
 */
object Host "docker-host" {
  address = "172.17.0.1"
  check_command = "hostalive"
  vars.os = "Linux"
  vars.http_vhosts["observe-api"] = {
    http_uri = "/observe/api/health"
    http_port = 3000
  }
}
