backend = "redis";
new_schema = true;
min_tokens = 11;
min_learns = 200;

cache {
}

autolearn {
  spam_threshold = 6.0;
  junk_threshold = 4.0;
  ham_threshold = -0.5;
  check_balance = true;
  min_balance = 0.9;
  options {
    probability_check {
      spam_min = 0.92;
      ham_max = 0.08;
    }
    logging {
      enabled = true;
    }
  }
}