servers = "redis:6379";
timeout = 20;
max_profiles = 3;
spam_score_threshold = 0.92;
ham_score_threshold = 0.08;
symbol_spam = "NEURAL_SPAM";
symbol_ham = "NEURAL_HAM";

train {
  max_trains = 1000;
  max_usages = 40;
  learning_rate = 0.01;
  max_iterations = 25;
}