dynamic_rate_limit = true;

rates {
  user = {
    bucket = [
      {
        burst = 12;
        rate = "12 / 5m";
        message = "Too many outbound messages for authenticated user";
      },
      {
        burst = 40;
        rate = "40 / 1h";
        message = "Hourly outbound limit exceeded for authenticated user";
      }
    ];
  }
}
