authenticated_outbound {
  priority = high;
  authenticated = yes;
  apply {
    BAYES_SPAM = 8.0;
    NEURAL_SPAM = 6.0;
    MIME_BASE64_TEXT = 4.0;
    REPLYTO_DOM_NEQ_FROM_DOM = 6.0;
    URI_COUNT_ODD = 3.0;
    MANY_INVISIBLE_PARTS = 4.0;
    actions {
      reject = 12.0;
      "add header" = 4.0;
      greylist = null;
    }
  }
}
