-- Grant SST privileges for mariabackup
CREATE USER IF NOT EXISTS 'galera'@'localhost' IDENTIFIED BY 'galeraSST@2026';
GRANT RELOAD, PROCESS, LOCK TABLES, REPLICATION CLIENT ON *.* TO 'galera'@'localhost';
CREATE USER IF NOT EXISTS 'galera'@'%' IDENTIFIED BY 'galeraSST@2026';
GRANT RELOAD, PROCESS, LOCK TABLES, REPLICATION CLIENT ON *.* TO 'galera'@'%';
FLUSH PRIVILEGES;
