module(load="imuxsock")

$RepeatedMsgReduction off
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

mail.*    action(type="omfile" file="/proc/1/fd/1")
authpriv.* action(type="omfile" file="/proc/1/fd/1")
*.info;mail.none;authpriv.none;cron.none action(type="omfile" file="/proc/1/fd/1")