ServerName results.com.br

<VirtualHost *:80>
    ServerAdmin infra@results.com.br
    DocumentRoot /var/www/html/results

    <Directory /var/www/html/results>
        AllowOverride All
        Options FollowSymLinks
        Require all granted
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>